# Generated by Django 3.2 on 2021-05-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='email',
            field=models.EmailField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
